# -*- coding: utf-8 -*-
"""flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZ3xeVlXIQ2lOffmSGwq5EgPM0FtUoSx
"""

pip install flask
from flask import Flask, request, jsonify

app = Flask(__name__)

# Simulação da rede offline
nodes = {}

@app.route('/register_device', methods=['POST'])
def register_device():
    data = request.get_json()
    device_id = data['device_id']
    nodes[device_id] = {
        'messages': [],
        'location': data.get('location', {})
    }
    return jsonify({"message": f"Device {device_id} registered successfully."}), 200

@app.route('/send_message', methods=['POST'])
def send_message():
    data = request.get_json()
    sender_id = data['sender_id']
    recipient_id = data['recipient_id']
    message = data['message']

    if recipient_id in nodes:
        nodes[recipient_id]['messages'].append({
            'sender': sender_id,
            'message': message
        })
        return jsonify({"message": "Message delivered."}), 200
    else:
        return jsonify({"error": "Recipient not found."}), 404

@app.route('/get_messages/<device_id>', methods=['GET'])
def get_messages(device_id):
    if device_id in nodes:
        return jsonify(nodes[device_id]['messages']), 200
    else:
        return jsonify({"error": "Device not found."}), 404

if __name__ == '__main__':
    app.run(debug=True)